### ISSUE TITLE
zip.hpp doesn't compile with gcc 8.2.1

### ISSUE THREAD

**Issue by ilyalesokhin-starkware** [ryanhaining/cppitertools#48]
$ g++ examples/zip_examples.cpp -I ./ -std=c++17
In file included from examples/zip_examples.cpp:1:
./zip.hpp: In instantiation of ‘class iter::impl::Zipped<std::tuple<std::vector<int, std::allocator<int> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&>, 0, 1>::Iterator<std::tuple<std::vector<int, std::allocator<int> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&>, iter::impl::iterator_tuple_type, iter::impl::iterator_deref_tuple>’:
examples/zip_examples.cpp:13:46:   required from here
./zip.hpp:41:60: error: template parameter ‘template<class TupleType, long unsigned int ...Is> template<class> class IteratorTuple’
   template <typename TupleTypeT, template <typename> class IteratorTuple,
                                                            ^~~~~~~~~~~~~
./zip.hpp:46:18: error: redeclared here as ‘template<class> class<template-parameter-1-2>’
     friend class Iterator;
                  ^~~~~~~~

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC)

**Comment by ryanhaining** [comment]
confirmed, repro with 8.2.0

**Comment by ilyalesokhin-starkware** [comment]
Btw, the stuff we are using works fine when I comment out this friend deceleration.
Can you explain why it is there?

**Comment by ryanhaining** [comment]
const iterators need to compare with non-const iterators, if you cd into test/ and run `scons test_zip` you'll see a ton of errors without the friend declaration

**Comment by ryanhaining** [comment]
Bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87651

not sure if I can provide any fix other than making the iterator data members public :/

**Comment by ryanhaining** [comment]
and a similar bug breaking filter. gcc really slipped up on 8 I guess https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87652

**Comment by dnbaker** [comment]
Is this fixed in `master` now?

**Comment by ryanhaining** [comment]
Yes, fixed in a recent commit that autoclosed the issue. Let me know if you
see the problem still
